---

- name: Create the Alertmanager group
  group:
    name: "{{ alertmanager_group }}"
    system: true

- name: Create the Alertmanager user
  user:
    name: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    system: yes
    createhome: no

- include: github-alertmanager-release.yml
  when: not alertmanager_release_url

- name: Make sure the Alertmanager install directory exists
  file:
    dest: "{{ alertmanager_install_path }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755

- name: Get the name of the Alertmanager release archive
  set_fact:
    _alertmanager_archive: "{{ alertmanager_release_url | basename }}"

- name: Set the Alertmanager installation path
  set_fact:
    _alertmanager_install_path: "{{ alertmanager_install_path }}/{{ _alertmanager_archive | regex_replace('\\.zip|\\.gz|\\.tar|\\.tgz|\\.bzip','') }}"

- name: Download Alertmanager
  unarchive:
    src: "{{ alertmanager_release_url }}"
    dest: "{{ alertmanager_install_path }}"
    creates: "{{ _alertmanager_install_path }}/alertmanager"
    remote_src: yes

- name: Symlink the Alertmanager binaries
  file:
    src: "{{ _alertmanager_install_path }}/{{ item }}"
    dest: "{{ alertmanager_bin_path }}/{{ item }}"
    state: link
  notify: restart alertmanager
  with_items:
    - alertmanager
    - amtool
