---

- name: Set the Github releases API endpoint
  set_fact:
    _alertmanager_github_api_url: |-
      {% if alertmanager_release_tag == 'latest' %}
      https://api.github.com/repos/prometheus/alertmanager/releases/latest
      {% else %}
      https://api.github.com/repos/prometheus/alertmanager/releases/tags/{{ alertmanager_release_tag }}
      {% endif %}

- name: Fetch the latest Alertmanager release information from Github
  uri:
    url: "{{ _alertmanager_github_api_url }}"
    method: GET
  register: _alertmanager_github_release
  until: _alertmanager_github_release.status == 200
  retries: 5
  delay: 15

- name: Get the Alertmanager latest release tag
  set_fact:
    alertmanager_release_tag: "{{ _alertmanager_github_release['json'] | json_query('tag_name') }}"
  when: alertmanager_release_tag == "latest"

- name: Set the name of the Alertmanager release artifact
  set_fact:
    _alertmanager_release_build: "{{ hostvars[inventory_hostname] | alertmanager_release_build(alertmanager_release_tag) }}"

- name: Make sure the Alertmanager install directory exists
  file:
    dest: "{{ alertmanager_install_path }}"
    state: directory

- name: Download Alertmanager
  unarchive:
    src: "{{ _alertmanager_github_release['json'] | json_query(_alertmanager_release_asset_url_query) }}"
    dest: "{{ alertmanager_install_path }}"
    creates: "{{ alertmanager_install_path }}/{{ _alertmanager_release_build }}/alertmanager"
    remote_src: yes
  vars:
    _alertmanager_release_asset_url_query: "assets[?name=='{{ _alertmanager_release_build }}.tar.gz'] | [0].browser_download_url"

- name: Symlink the Alertmanager binaries
  file:
    src: "{{ alertmanager_install_path }}/{{ _alertmanager_release_build }}/{{ item }}"
    dest: "{{ alertmanager_bin_path }}/{{ item }}"
    state: link
  with_items:
    - alertmanager
    - amtool

- name: Create the Alertmanager group
  group:
    name: "{{ alertmanager_group }}"
    system: true

- name: Create the Alertmanager user
  user:
    name: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    system: yes
    createhome: no
