---

- name: restart alertmanager
  service:
    name: alertmanager
    state: restarted

- name: reload alertmanager
  service:
    name: alertmanager
    state: reloaded

- name: reload systemd and restart alertmanager
  command: systemctl daemon-reload
  notify: restart alertmanager
  tags:
    - skip_ansible_lint
